package com.cuize.activity.dao.domain;

public class ActivityUserctl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_userctl.id
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_userctl.openid
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_userctl.id
     *
     * @return the value of activity_userctl.id
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_userctl.id
     *
     * @param id the value for activity_userctl.id
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_userctl.openid
     *
     * @return the value of activity_userctl.openid
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_userctl.openid
     *
     * @param openid the value for activity_userctl.openid
     *
     * @mbggenerated Thu Mar 31 11:25:42 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }
}