package com.cuize.activity.dao.domain;

import java.util.Date;

public class ActivityAward {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.activity_id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Integer activityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.award_name
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private String awardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.total_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Integer totalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.remain_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Integer remainCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.award_url
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private String awardUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.update_time
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.probability
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Double probability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.activity_date
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private String activityDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.version
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.id
	 * @return  the value of activity_award.id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.id
	 * @param id  the value for activity_award.id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.activity_id
	 * @return  the value of activity_award.activity_id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.activity_id
	 * @param activityId  the value for activity_award.activity_id
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.award_name
	 * @return  the value of activity_award.award_name
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public String getAwardName() {
		return awardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.award_name
	 * @param awardName  the value for activity_award.award_name
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setAwardName(String awardName) {
		this.awardName = awardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.total_count
	 * @return  the value of activity_award.total_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Integer getTotalCount() {
		return totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.total_count
	 * @param totalCount  the value for activity_award.total_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.remain_count
	 * @return  the value of activity_award.remain_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Integer getRemainCount() {
		return remainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.remain_count
	 * @param remainCount  the value for activity_award.remain_count
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setRemainCount(Integer remainCount) {
		this.remainCount = remainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.award_url
	 * @return  the value of activity_award.award_url
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public String getAwardUrl() {
		return awardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.award_url
	 * @param awardUrl  the value for activity_award.award_url
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setAwardUrl(String awardUrl) {
		this.awardUrl = awardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.update_time
	 * @return  the value of activity_award.update_time
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.update_time
	 * @param updateTime  the value for activity_award.update_time
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.probability
	 * @return  the value of activity_award.probability
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Double getProbability() {
		return probability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.probability
	 * @param probability  the value for activity_award.probability
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setProbability(Double probability) {
		this.probability = probability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.activity_date
	 * @return  the value of activity_award.activity_date
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public String getActivityDate() {
		return activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.activity_date
	 * @param activityDate  the value for activity_award.activity_date
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setActivityDate(String activityDate) {
		this.activityDate = activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.version
	 * @return  the value of activity_award.version
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.version
	 * @param version  the value for activity_award.version
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}