package com.cuize.activity.dao.mapper;

import com.cuize.activity.dao.domain.Activity;
import com.cuize.activity.dao.domain.ActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int countByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int deleteByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int insert(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int insertSelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	List<Activity> selectByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	Activity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Activity record,
			@Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int updateByExample(@Param("record") Activity record,
			@Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int updateByPrimaryKeySelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity
	 * @mbggenerated  Thu Mar 31 11:25:42 CST 2016
	 */
	int updateByPrimaryKey(Activity record);
}