package com.cuize.activity.dao.mapper;

import com.cuize.activity.dao.domain.ActivityUserctl;
import com.cuize.activity.dao.domain.ActivityUserctlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityUserctlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int countByExample(ActivityUserctlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int deleteByExample(ActivityUserctlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int insert(ActivityUserctl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int insertSelective(ActivityUserctl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	List<ActivityUserctl> selectByExample(ActivityUserctlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	ActivityUserctl selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ActivityUserctl record,
			@Param("example") ActivityUserctlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int updateByExample(@Param("record") ActivityUserctl record,
			@Param("example") ActivityUserctlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int updateByPrimaryKeySelective(ActivityUserctl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_userctl
	 * @mbggenerated  Wed Apr 06 11:15:31 CST 2016
	 */
	int updateByPrimaryKey(ActivityUserctl record);
}