package com.cuize.activity.dao.mapper;

import com.cuize.activity.dao.domain.ShopActivityRewardctl;
import com.cuize.activity.dao.domain.ShopActivityRewardctlExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ShopActivityRewardctlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int countByExample(ShopActivityRewardctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int deleteByExample(ShopActivityRewardctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int insert(ShopActivityRewardctl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int insertSelective(ShopActivityRewardctl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    List<ShopActivityRewardctl> selectByExample(ShopActivityRewardctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    ShopActivityRewardctl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") ShopActivityRewardctl record, @Param("example") ShopActivityRewardctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int updateByExample(@Param("record") ShopActivityRewardctl record, @Param("example") ShopActivityRewardctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int updateByPrimaryKeySelective(ShopActivityRewardctl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_activity_rewardctl
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    int updateByPrimaryKey(ShopActivityRewardctl record);
}