package com.cuize.product.dao.mapper;

import com.cuize.product.dao.domain.ShopActivity;
import com.cuize.product.dao.domain.ShopActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopActivityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int countByExample(ShopActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int deleteByExample(ShopActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int insert(ShopActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int insertSelective(ShopActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	List<ShopActivity> selectByExample(ShopActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	ShopActivity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ShopActivity record,
			@Param("example") ShopActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int updateByExample(@Param("record") ShopActivity record,
			@Param("example") ShopActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int updateByPrimaryKeySelective(ShopActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	int updateByPrimaryKey(ShopActivity record);
}