package com.cuize.product.dao.mapper;

import com.cuize.product.dao.domain.ShopActivityDraw;
import com.cuize.product.dao.domain.ShopActivityDrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopActivityDrawMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int countByExample(ShopActivityDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int deleteByExample(ShopActivityDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int insert(ShopActivityDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int insertSelective(ShopActivityDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	List<ShopActivityDraw> selectByExample(ShopActivityDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	ShopActivityDraw selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ShopActivityDraw record,
			@Param("example") ShopActivityDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int updateByExample(@Param("record") ShopActivityDraw record,
			@Param("example") ShopActivityDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int updateByPrimaryKeySelective(ShopActivityDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity_draw
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	int updateByPrimaryKey(ShopActivityDraw record);
}