package com.cuize.product.dao.domain;

import java.util.Date;

public class ShopActivityDraw {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.activity_id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Integer activityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.award_name
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private String awardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.total_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Integer totalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.surplus_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Integer surplusCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.award_url
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private String awardUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.update_time
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.winning_probability
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Double winningProbability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.activity_date
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private String activityDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity_draw.version
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.id
	 * @return  the value of shop_activity_draw.id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.id
	 * @param id  the value for shop_activity_draw.id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.activity_id
	 * @return  the value of shop_activity_draw.activity_id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.activity_id
	 * @param activityId  the value for shop_activity_draw.activity_id
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.award_name
	 * @return  the value of shop_activity_draw.award_name
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public String getAwardName() {
		return awardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.award_name
	 * @param awardName  the value for shop_activity_draw.award_name
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setAwardName(String awardName) {
		this.awardName = awardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.total_count
	 * @return  the value of shop_activity_draw.total_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Integer getTotalCount() {
		return totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.total_count
	 * @param totalCount  the value for shop_activity_draw.total_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.surplus_count
	 * @return  the value of shop_activity_draw.surplus_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Integer getSurplusCount() {
		return surplusCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.surplus_count
	 * @param surplusCount  the value for shop_activity_draw.surplus_count
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setSurplusCount(Integer surplusCount) {
		this.surplusCount = surplusCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.award_url
	 * @return  the value of shop_activity_draw.award_url
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public String getAwardUrl() {
		return awardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.award_url
	 * @param awardUrl  the value for shop_activity_draw.award_url
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setAwardUrl(String awardUrl) {
		this.awardUrl = awardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.update_time
	 * @return  the value of shop_activity_draw.update_time
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.update_time
	 * @param updateTime  the value for shop_activity_draw.update_time
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.winning_probability
	 * @return  the value of shop_activity_draw.winning_probability
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Double getWinningProbability() {
		return winningProbability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.winning_probability
	 * @param winningProbability  the value for shop_activity_draw.winning_probability
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setWinningProbability(Double winningProbability) {
		this.winningProbability = winningProbability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.activity_date
	 * @return  the value of shop_activity_draw.activity_date
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public String getActivityDate() {
		return activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.activity_date
	 * @param activityDate  the value for shop_activity_draw.activity_date
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setActivityDate(String activityDate) {
		this.activityDate = activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity_draw.version
	 * @return  the value of shop_activity_draw.version
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity_draw.version
	 * @param version  the value for shop_activity_draw.version
	 * @mbggenerated  Mon Mar 28 19:06:06 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public String toString() {
		return "ShopActivityDraw [id=" + id + ", awardName=" + awardName
				+ ", totalCount=" + totalCount + ", surplusCount="
				+ surplusCount + ", activityDate=" + activityDate
				+ ", version=" + version + "]";
	}
}