package com.cuize.product.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopActivityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public ShopActivityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andActivityNameIsNull() {
			addCriterion("activity_name is null");
			return (Criteria) this;
		}

		public Criteria andActivityNameIsNotNull() {
			addCriterion("activity_name is not null");
			return (Criteria) this;
		}

		public Criteria andActivityNameEqualTo(String value) {
			addCriterion("activity_name =", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameNotEqualTo(String value) {
			addCriterion("activity_name <>", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameGreaterThan(String value) {
			addCriterion("activity_name >", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
			addCriterion("activity_name >=", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameLessThan(String value) {
			addCriterion("activity_name <", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameLessThanOrEqualTo(String value) {
			addCriterion("activity_name <=", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameLike(String value) {
			addCriterion("activity_name like", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameNotLike(String value) {
			addCriterion("activity_name not like", value, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameIn(List<String> values) {
			addCriterion("activity_name in", values, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameNotIn(List<String> values) {
			addCriterion("activity_name not in", values, "activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameBetween(String value1, String value2) {
			addCriterion("activity_name between", value1, value2,
					"activityName");
			return (Criteria) this;
		}

		public Criteria andActivityNameNotBetween(String value1, String value2) {
			addCriterion("activity_name not between", value1, value2,
					"activityName");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNull() {
			addCriterion("begin_date is null");
			return (Criteria) this;
		}

		public Criteria andBeginDateIsNotNull() {
			addCriterion("begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andBeginDateEqualTo(Date value) {
			addCriterion("begin_date =", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotEqualTo(Date value) {
			addCriterion("begin_date <>", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThan(Date value) {
			addCriterion("begin_date >", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
			addCriterion("begin_date >=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThan(Date value) {
			addCriterion("begin_date <", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateLessThanOrEqualTo(Date value) {
			addCriterion("begin_date <=", value, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateIn(List<Date> values) {
			addCriterion("begin_date in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotIn(List<Date> values) {
			addCriterion("begin_date not in", values, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateBetween(Date value1, Date value2) {
			addCriterion("begin_date between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andBeginDateNotBetween(Date value1, Date value2) {
			addCriterion("begin_date not between", value1, value2, "beginDate");
			return (Criteria) this;
		}

		public Criteria andTotalDayIsNull() {
			addCriterion("total_day is null");
			return (Criteria) this;
		}

		public Criteria andTotalDayIsNotNull() {
			addCriterion("total_day is not null");
			return (Criteria) this;
		}

		public Criteria andTotalDayEqualTo(Integer value) {
			addCriterion("total_day =", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayNotEqualTo(Integer value) {
			addCriterion("total_day <>", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayGreaterThan(Integer value) {
			addCriterion("total_day >", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayGreaterThanOrEqualTo(Integer value) {
			addCriterion("total_day >=", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayLessThan(Integer value) {
			addCriterion("total_day <", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayLessThanOrEqualTo(Integer value) {
			addCriterion("total_day <=", value, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayIn(List<Integer> values) {
			addCriterion("total_day in", values, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayNotIn(List<Integer> values) {
			addCriterion("total_day not in", values, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayBetween(Integer value1, Integer value2) {
			addCriterion("total_day between", value1, value2, "totalDay");
			return (Criteria) this;
		}

		public Criteria andTotalDayNotBetween(Integer value1, Integer value2) {
			addCriterion("total_day not between", value1, value2, "totalDay");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_activity
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_activity
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 28 18:14:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}