package com.cuize.product.dao.domain;

public class ShopActivityRewardctl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_activity_rewardctl.id
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_activity_rewardctl.openid
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_activity_rewardctl.id
     *
     * @return the value of shop_activity_rewardctl.id
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_activity_rewardctl.id
     *
     * @param id the value for shop_activity_rewardctl.id
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_activity_rewardctl.openid
     *
     * @return the value of shop_activity_rewardctl.openid
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_activity_rewardctl.openid
     *
     * @param openid the value for shop_activity_rewardctl.openid
     *
     * @mbggenerated Mon Mar 28 18:47:24 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }
}