package com.cuize.product.dao.domain;

import java.util.Date;

public class ShopActivity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity.id
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity.activity_name
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	private String activityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity.begin_date
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_activity.total_day
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	private Integer totalDay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity.id
	 * @return  the value of shop_activity.id
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity.id
	 * @param id  the value for shop_activity.id
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity.activity_name
	 * @return  the value of shop_activity.activity_name
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public String getActivityName() {
		return activityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity.activity_name
	 * @param activityName  the value for shop_activity.activity_name
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity.begin_date
	 * @return  the value of shop_activity.begin_date
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity.begin_date
	 * @param beginDate  the value for shop_activity.begin_date
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_activity.total_day
	 * @return  the value of shop_activity.total_day
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public Integer getTotalDay() {
		return totalDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_activity.total_day
	 * @param totalDay  the value for shop_activity.total_day
	 * @mbggenerated  Mon Mar 28 18:23:01 CST 2016
	 */
	public void setTotalDay(Integer totalDay) {
		this.totalDay = totalDay;
	}
}